"""
Django settings for freshjuice project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u!^^+i%_w&zjy+gx@#0flgj#&94$xi__8eei6fj1xbh&dnsb#p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # user defined


    'crispy_forms',
    'dashboard',
    'home',
    'products',
    'blog',
    'accounts',
    'services',
    'payments',


    # dependencies
    'django.contrib.sites',  # Required for Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Add social providers you want to use, e.g.,:
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',

    # 'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.contrib.auth.middleware.RemoteUserMiddleware",
    # 'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
    'allauth.account.middleware.AccountMiddleware',  # Add this line

    # 'social_django.middleware.SocialAuthExceptionMiddleware',  # add this

]

ROOT_URLCONF = 'freshjuice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'social_django.context_processors.backends',  # add this

            ],
        },
    },
]

WSGI_APPLICATION = 'freshjuice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL='accounts.User'


AUTHENTICATION_BACKENDS = [
    #'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
]
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_URL = 'accounts:logout'
LOGOUT_REDIRECT_URL = 'account_login'
SOCIAL_AUTH_FACEBOOK_KEY = "#############"
SOCIAL_AUTH_FACEBOOK_SECRET = "############"
ACCOUNT_EMAIL_REQUIRED = True  # Require email during signup
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Require email verification
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True  # Redirect after login
ACCOUNT_USERNAME_REQUIRED = False  # Allow users to log in with email only
ACCOUNT_AUTHENTICATION_METHOD = 'email'
SOCIALACCOUNT_EMAIL_AUTHENTICATION='True'
SOCIALACCOUNT_AUTO_SIGNUP='True'
SOCIALACCOUNT_QUERY_EMAIL = True  # Get email address from Google
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.MySocialAccountAdapter'

#for extra info
SOCIAL_AUTH_FACEBOOK_SCOPE = [
    'email',
]

SITE_ID = 1


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jeremymayaka96@gmail.com'
EMAIL_HOST_PASSWORD = 'bfdu dpyx nxwk zbrp'  # Use an app password if 2FA is enabled


# settings.py


# Initialize environment variables
# settings.py
MPESA_CONSUMER_KEY = "43x4pUkMeFMcsVAvCcn8ajuLbqGdtMd8wbWRXp5dQG1H7FpH"
MPESA_CONSUMER_SECRET = "iZ7vIHjn6WRnYNQJgCG1S9GbU85WoJqXQQng4GTJcFgr867d83y3Ax3SyemKHICU"
MPESA_SHORTCODE = "174379"  # Default test shortcode
MPESA_PASSKEY = "your_stk_push_passkey"  # Ensure you replace this with your actual passkey
MPESA_BASE_URL = "https://sandbox.safaricom.co.ke"  # Use live URL for production
CALLBACK_URL = "https://abc123.ngrok.io/payments/confirmation/"
