# Generated by Django 5.1.2 on 2024-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/avatars/default.jpg', upload_to='media/avatars/'),
        ),
    ]
