# Generated by Django 5.1.2 on 2024-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_receive_newsletter_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/avatars/undraw_profile_2.svg', upload_to='media/avatars/'),
        ),
    ]
