# Generated by Django 5.1.2 on 2024-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/img/undraw_profile_2.svg', upload_to='media/avatars/'),
        ),
    ]
