# Generated by Django 5.1.2 on 2024-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_receive_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/img/undraw_profile_2.svg', upload_to='avatars/'),
        ),
    ]
