# Generated by Django 5.1.2 on 2024-10-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_google_picture_user_google_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='img/undraw_profile_2.svg', upload_to='avatars/'),
        ),
    ]
